#-------------------------------
# Site Settings
title: Flight Free USA
description: Menca personal blogging theme for Jekyll
logo: /images/FLIGHTFREEUSA_black.jpg 
logo_dark: /images/FLIGHTFREEUSA_white.webp
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Campaign"
      url: "/"
    - title: "Learn More"
      url: "/learn/"
    - title: "Alternatives"
      url: "/alternatives/"
    - title: "Press"
      url: "/press/"
    - title: "Pledge to Fly Less"
      url: "/pledge/"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: One flight, One seat, One Ton of CO2.
  hero_description: We are in a dire climate emergency, flying fries the planet and yet there are about 125,000 daily commercial flights in the world and growing. Pledge to fly less in 2026 for the climate!
  hero_image: '/images/hero.webp'


#-------------------------------
# Newsletter
mailchimp:
  enable: true
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Subscribe here
  mailchimp_button_text: Get a new tip


#-------------------------------
# Author Settings
author:
  # author_name: Ariella Grannett
  author_bio: 'Together, we can reduce emissions, change the norm and lay the foundations for strong climate policy. Contact: PledgeFlightFree@gmail.com'
  author_avatar: '/images/FLIGHTFREEUSA_black.jpg'




social:
- {icon: "fa-brands fa-bluesky", name: "Twitter", link: "https://bsky.app/profile/flightfreeusa.bsky.social"}
- {icon: "fa-brands fa-square-facebook", name: "Facebook", link: "https://www.facebook.com/flightfreeUSA/"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/flightfreeusa/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Gallery Footer Section
# gallery:
#   enable: true
#   gallery_title: Gallery
#   gallery_columns: 3
#   gallery_images:
#     - alt: 'Rest'
#       url: '/images/100.jpg'
#     - alt: 'Lifestyle'
#       url: '/images/101.jpg'
#     - alt: 'Hobby'
#       url: '/images/102.jpg'
#     - alt: 'Notes'
#       url: '/images/103.jpg'
#     - alt: 'Rest'
#       url: '/images/104.jpg'
#     - alt: 'Hobby'
#       url: '/images/105.jpg'
#     - alt: 'Fashion'
#       url: '/images/106.jpg'
#     - alt: 'Notes'
#       url: '/images/107.jpg'
#     - alt: 'Rest'
#       url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  form_id: info@flightfree.org # Add your form_id
  description: Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menca theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
# disqus:
#   enable: true
#   disqus_identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


# #-------------------------------
# # Google Analytics
# google_analytics: # Add your GA Tracking Id
